### ISSUE TITLE
Breaking change in 2.4.1: Keys are now symbolized

### ISSUE THREAD

**Issue by tf** [zapnap/resque_mailer#100]
#97 breaks our app. When [receiving a hash in a mailer method](https://github.com/codevise/pageflow/blob/master/app/mailers/pageflow/user_mailer.rb#L6), the keys used to be strings. Now they are symbols.

**Comment by zapnap** [comment]
Thanks for reporting this -- surprised it hasn't bitten anyone else! I'll see if I can get an update out this week. In the meantime, PRs always welcome :). Seems that the support for block syntax added by @jogaco (requiring symbolized keys) inadvertently broke this -- should add some tests around that requirement.

https://github.com/zapnap/resque_mailer/commit/3feb4a462892a8a3520420caded63443fe9f0f28

**Comment by jogaco** [comment]
Sorry about this. I've submitted #101 as a quick fix

**Comment by zapnap** [comment]
Big thanks to @jogaco for sorting this so quickly. v2.4.2 has been released.
