### ISSUE TITLE
Support For Argument Keyword / Named Parameter

### ISSUE THREAD

**Issue by chopraanmol1** [zapnap/resque_mailer#104]
resque_mailer 2.4.1 works fine for named parameter but 2.4.2 and 2.4.3 fails (tested in ruby 2.3.1) as they are converted in HashWithIndifferentAccess.

Ruby generally calls to_hash method (for non hash object) on last parameter before mapping to named parameter. Which is not the case for  HashWithIndifferentAccess as it inherits from Hash  

Adding a delegator class which points to HashWithIndifferentAccess object with custom to_hash ( symbolized key )
 will solve all of previous as well as current Issue.

Check the below code snippet to understand issue and possible solution

```

require 'active_support/hash_with_indifferent_access'

def test_method(param1:,param2:) ; puts [param1,param2] ; end

class SymbolizedHashWithIndifferentAccess < Delegator
  def initialize(obj = {})
    @delegate_sd_obj = HashWithIndifferentAccess.new obj
  end

  def to_hash
    stringified_hash  = super
    stringified_hash.symbolize_keys!
    stringified_hash
  end

  def __getobj__
    @delegate_sd_obj
  end

  def __setobj__(obj)
    @delegate_sd_obj = HashWithIndifferentAccess.new obj
  end
end


hash_object = SymbolizedHashWithIndifferentAccess.new param1: 'param one', param2: 'param two'
# Will Work (Proposed Scenario)
test_method hash_object

# Won't Work (Current Scenario)
test_method hash_object.__getobj__


```

**Comment by zapnap** [comment]
Thanks for this. Will take a look shortly!
