### ISSUE TITLE
unnecessary "allow" invalidates custom serializer test 

### ISSUE THREAD

**Issue by masukomi** [zapnap/resque_mailer#106]
```
    it "serializes the arguments with the custom serializer" do
      allow(TestSerializer).to receive(:serialize)
      expect(TestSerializer).to receive(:serialize)
      Rails3Mailer.test_mail(Rails3Mailer::MAIL_PARAMS).deliver
    end

```
the allow line basically says "even if this serializer doesn't respond to `serialize` make sure it receives a call to it" which... is valid to some degree. You're just testing that it gets called not that it works, but also hides potential problems and makes the test a bit weird. If you're ONLY concerned with testing that it gets called then it makes more sense to use a double instead of an _actual_ serializer. 

the tests pass just fine if you comment out this line, which is expected since it really has a serialize method.

I'll happily create a PR with either change, or maybe one test with the double plus the allow and one test with the actual serializer and without the allow.

**Comment by zapnap** [comment]
Ahaha yes good catch. I'll fix. Thanks for reporting.
