### ISSUE TITLE
DateTime objects are being converted to strings when passed to Mailer

### ISSUE THREAD

**Issue by monfresh** [zapnap/resque_mailer#83]
I'm running into an issue where I'm passing a DateTime object as one of the parameters of a mailer, but when `Resque::Mailer` processes it, it treats it as a String.

Here is my code:

I have a rake task that calls `AdminMailer.hourly_report`:
```ruby
desc 'Delivers hourly usage report'
  task deliver_hourly_report: :environment do
    Kernel.puts '     Delivering hourly report'

    time_end = Time.now.utc.beginning_of_hour
    time_start = time_end - 1.hour

    new_users_count = User.where('account_type = ? AND created_at BETWEEN ? AND ?', 0, time_start, time_end).count
    total_users_count = User.where('account_type = ? AND created_at <= ?', 0, time_end).count

    AdminMailer.hourly_report(new_users_count, total_users_count, time_start, time_end).deliver
  end
end
```
The hourly report then takes those parameters and uses them in the subject and body of the email:
```ruby
class AdminMailer < ActionMailer::Base
  include Resque::Mailer

  default from: 'user@example.com'

  def hourly_report(new_users_count, total_users_count, time_start, time_end)
    @start_friendly = time_start.strftime('%m-%d-%Y %H:%M')
    @end_friendly = time_end.strftime('%m-%d-%Y %H:%M')
    @new_users_count = new_users_count
    @total_users_count = total_users_count

    mail(to: 'foo@bar.com', subject: "[Admin] Hourly Report #{@start_friendly} - #{@end_friendly}")
  end
end
```

If I run this without including `Resque:Mailer`, it works just fine. But with `Resque:Mailer`, I get the following error:

```ruby
Unable to deliver email [hourly_report]: undefined method `strftime' for "2015-05-19T02:00:00.000Z":String
```

Why is `Resque::Mailer` converting the DateTime parameters into a String?

**Comment by monfresh** [comment]
I know I can perform the formatting in the task and pass in a String to the mailer, which is what I did to fix this issue, but I'm still curious to know why the arguments are being transformed.

**Comment by yoavmatchulsky** [comment]
All the parameters are being serialized into JSON to be saved in Redis, which means that DateTime objects gets turned into String

Its the same notion as passing object ids instead of the object instance (e.g. user_id intead of User.find(id))

**Comment by zapnap** [comment]
Yup, exactly! We'd toyed with the idea of automatically deserializing objects, but there are a few gotchas there and not a ton of value to justify it imo. In most cases jobs are designed to look up an object and handle it in some way, so pretty simple.

**Comment by monfresh** [comment]
Got it, thanks!
