### ISSUE TITLE
`deliver_at` broken in v2.3.0

### ISSUE THREAD

**Issue by naomipol** [zapnap/resque_mailer#87]
I've used the `deliver_at` method with v2.2.7 gem - all worked fine,
But as I updated to v2.3.0 inorder to use the new active-record serializer the `deliver_at` stopped working.
I must say that the `deliver` method works ok.

using rails 4.1.8

```ruby
#Gemfile.lock
resque (1.25.2)
resque-scheduler (4.2.0)
resque_mailer (2.3.0)
```
Any idea what could be causing this?

**Comment by zapnap** [comment]
Not sure but will take a look as soon as I can find some free time. What version of resque-scheduler are you using?

**Comment by naomipol** [comment]
as I mentioned `4.2.0`
Thanks

**Comment by zapnap** [comment]
@naomipol give current master a shot. If that's working for you, I'll release 2.3.1 with the fix.

**Comment by naomipol** [comment]
Great fix! Its now all working, thanks.
waiting for the release...

**Comment by zapnap** [comment]
v2.3.1 has been released!
