### ISSUE TITLE
Unknown key: address

### ISSUE THREAD

**Issue by dcalixto** [zapnap/resque_mailer#89]
Someone is having this issue?

```
  include Resque::Mailer


  def registration_confirmation(user_id)
    user = User.find(user_id)

    mail(to: "#{user.email}", subject: 'Confirm register', &:html)
  end

```

     UserMailer 
Arguments

 ```
   "registration_confirmation"
    [{"address"=>nil, "address_supplement"=>nil, "admin"=>false, "auth_token"=>"rFHzIr_p6CXaE1jbO0ySXA", "avatar"=>{"url"=>"/assets/fallback/avatar.png", "mobile"=>{"url"=>"/assets/fallback/mobile_avatar.png"}, "thumb"=>{"url"=>"/assets/fallback/thumb_avatar.png"}}, "banned"=>false, "banner"=>{"url"=>"/assets/fallback/img.png", "thumb"=>{"url"=>"/assets/fallback/thumb_img.png"}, "mobile"=>{"url"=>"/assets/fallback/mobile_img.png"}}, "city_id"=>nil, "confirm_token"=>"QA69bTLjyQl5T3nhYwZVlg", "created_at"=>"2016-07-16T19:30:43-03:00", "email"=>"calixtodaniel@gmail.com", "email_confirmed"=>false, "gender"=>"M", "id"=>9, "ip_address"=>nil, "last_read_messages_at"=>"2016-07-16T19:30:43-03:00", "latitude"=>nil, "login_at"=>nil, "longitude"=>nil, "name"=>"daniel", "neighborhood"=>nil, "oauth_expires_at"=>nil, "oauth_token"=>nil, "otp_counter"=>nil, "otp_secret_key"=>nil, "password_digest"=>"$2a$10$t1Py.m/Rfb3FMryV2RGmuOpel7kx9vrCQljXRKjZlc9RkCBDWfuj6", "password_reset_at"=>nil, "password_reset_token"=>nil, "phone"=>nil, "postal_code"=>nil, "provider"=>nil, "slug"=>"daniel", "state_id"=>nil, "surname"=>"daniel", "uid"=>nil, "updated_at"=>"2016-07-16T19:30:43-03:00"}]
```

**Comment by zapnap** [comment]
This works *without* Resque::Mailer included?

**Comment by dcalixto** [comment]
thank you @zapnap, and  yes works.

**Comment by zapnap** [comment]
To be clear: your example works fine if you're *not* using (including) ResqueMailer but does not work once you add the include? I'm not familiar with the block syntax here, and it's not super clear to me what your issue is from the details you've provided. More details about your environment (version of Rails, Resque, ResqueMailer, the exact error message with a stack trace) would be helpful here.

**Comment by zapnap** [comment]
Closing this as it's been several days without a response and it's impossible to investigate further without details. Please reopen with more details if it continues to be a problem.

**Comment by dcalixto** [comment]
sorry for the delay @zapnap 

right the rails is 3.2.22


and the stack trace is:





"user_welcome"
[{"address"=>nil, "address_supplement"=>nil, "admin"=>false, "auth_token"=>"-O-vuMuW6oLEX-y6Qb6b8Q", "avatar"=>{"url"=>"/assets/fallback/avatar.png", "mobile"=>{"url"=>"/assets/fallback/mobile_avatar.png"}, "thumb"=>{"url"=>"/assets/fallback/thumb_avatar.png"}}, "banned"=>false, "banner"=>{"url"=>"/assets/fallback/img.png", "thumb"=>{"url"=>"/assets/fallback/thumb_img.png"}, "mobile"=>{"url"=>"/assets/fallback/mobile_img.png"}}, "city_id"=>nil, "confirm_token"=>nil, "created_at"=>"2016-08-20T21:01:33-03:00", "email"=>"dcalixto555@gmail.com", "email_confirmed"=>false, "facebook"=>nil, "gender"=>"M", "id"=>3, "ip_address"=>nil, "last_read_messages_at"=>"2016-08-20T21:01:33-03:00", "latitude"=>nil, "login_at"=>nil, "longitude"=>nil, "name"=>"daniel", "neighborhood"=>nil, "oauth_expires_at"=>nil, "oauth_token"=>nil, "otp_counter"=>nil, "otp_secret_key"=>nil, "password_digest"=>"$2a$10$krwhuG9cFIopKUDZCJR6aeVeP7SfUn3SLrLjtcwj26XBBYIAjtfve", "password_reset_at"=>nil, "password_reset_token"=>nil, "phone"=>nil, "postal_code"=>nil, "provider"=>nil, "slug"=>"daniel", "state_id"=>nil, "surname"=>"daniel", "twitter"=>nil, "uid"=>nil, "updated_at"=>"2016-08-20T21:01:33-03:00"}]
Exception
NoMethodError
Error
undefined method `perform' for UserMailer:Class
