### ISSUE TITLE
Making environment available to resque workers

### ISSUE THREAD

**Issue by kbighorse** [zapnap/resque_mailer#9]
Trying to call Model.find in my mailer deliver method, but getting this error in Resque:

uninitialized constant ModelMailer::Model

I can send mail synchronously, so I'm deducing that my worker isn't loading the environment correctly.  I've tried:

$ QUEUE=\* rake environment resque:work

and I've tried the rake setup task:
# lib/tasks/resque.rake

require "resque/tasks"

task "resque:setup" => :environment

Still the same error.  Really want to avoid passing a full object to the deliver method, but will until I can figure this out.  Thank you for your help.

Kimball

**Comment by chickensmitten** [comment]
@zapnap THANK YOU! I was facing the fixnum issue as well! When I restarted, everything is working fine! Wont be pulling my hair out! XD
