### ISSUE TITLE
Multiple Ques

### ISSUE THREAD

**Issue by tonyvince** [zapnap/resque_mailer#93]
Mails are queued using default queue `mailer`. I would like to know is it possible to set up multiple queues, say `apply_mailer`, `approve_mailer` etc.. How to configure and use them ?

**Comment by zapnap** [comment]
You should just be able to set the `@queue` on the mailer, like you would in any Resque worker class. Ex:

    class Notifier < ApplicationMailer
      include Resque::Mailer
      @queue = 'my_special_queue'
