### ISSUE TITLE
Unknown key: address -reopen issue

### ISSUE THREAD

**Issue by dcalixto** [zapnap/resque_mailer#94]
sorry for the delay @zapnap

right the rails is 3.2.22

and the stack trace is:

"user_welcome"
[{"address"=>nil, "address_supplement"=>nil, "admin"=>false, "auth_token"=>"-O-vuMuW6oLEX-y6Qb6b8Q", "avatar"=>{"url"=>"/assets/fallback/avatar.png", "mobile"=>{"url"=>"/assets/fallback/mobile_avatar.png"}, "thumb"=>{"url"=>"/assets/fallback/thumb_avatar.png"}}, "banned"=>false, "banner"=>{"url"=>"/assets/fallback/img.png", "thumb"=>{"url"=>"/assets/fallback/thumb_img.png"}, "mobile"=>{"url"=>"/assets/fallback/mobile_img.png"}}, "city_id"=>nil, "confirm_token"=>nil, "created_at"=>"2016-08-20T21:01:33-03:00", "email"=>"dcalixto555@gmail.com", "email_confirmed"=>false, "facebook"=>nil, "gender"=>"M", "id"=>3, "ip_address"=>nil, "last_read_messages_at"=>"2016-08-20T21:01:33-03:00", "latitude"=>nil, "login_at"=>nil, "longitude"=>nil, "name"=>"daniel", "neighborhood"=>nil, "oauth_expires_at"=>nil, "oauth_token"=>nil, "otp_counter"=>nil, "otp_secret_key"=>nil, "password_digest"=>"$2a$10$krwhuG9cFIopKUDZCJR6aeVeP7SfUn3SLrLjtcwj26XBBYIAjtfve", "password_reset_at"=>nil, "password_reset_token"=>nil, "phone"=>nil, "postal_code"=>nil, "provider"=>nil, "slug"=>"daniel", "state_id"=>nil, "surname"=>"daniel", "twitter"=>nil, "uid"=>nil, "updated_at"=>"2016-08-20T21:01:33-03:00"}]
Exception
NoMethodError
Error
undefined method `perform' for UserMailer:Class

**Comment by zapnap** [comment]
Can you please supply full details here? (version of Resque, Resque::Mailer, the method definition for your mailer). Posting a small sample app that illustrates the problem would be helpful in isolating the issue.

**Comment by zapnap** [comment]
closing this due to lack of response / information
